### ISSUE TITLE
plot of omicsData object always has "Reference Standardized" in the title

### ISSUE THREAD

**Issue by stratkg** [pmartR/pmartR#247]
This is true even with no reference-based normalization has been applied. Other plot title logic should also be checked.

**Comment by clabornd** [comment]
Hi Kelly, going through some issues, sorry this one slipped through the cracks.  Yes this issue persists, and has it's origins in 2021!!    

```
> myobj <- pmartRdata::pro_object
> myobj <- myobj |> group_designation(main_effects = "Phenotype")
> myobj <- myobj |> normalize_global(subset_fn = "all", norm_fn="median", apply_norm = T)
> plot(myobj)
```

This line is the offender:  https://github.com/pmartR/pmartR/blob/11d0bcda309066c24f4e75c3b26131a04dee4c35/R/plot_fns.R#L5338

I think we just need to add a check for isobaric datatype and use `get_isobaric_norm` instead of `get_data_norm`.
