### ISSUE TITLE
protein_quant() -- Argument emeta_cols doesn't seem to keep the columns specified?

### ISSUE THREAD

**Issue by rarichardson92** [pmartR/pmartR#302]
This guy doesn't keep "ProteinList" :(

`mypepData <- group_designation(omicsData = pep_object, main_effects = c("Phenotype"))`
`mypepData = edata_transform(omicsData = mypepData, "log2")`

`imdanova_Filt <- imdanova_filter(omicsData = mypepData)`
`mypepData <- applyFilt(filter_object = imdanova_Filt, omicsData = mypepData, min_nonmiss_anova = 2)`

`imd_anova_res <- imd_anova(omicsData = mypepData, test_method = 'comb',
                           pval_adjust_a_multcomp = 'bon', pval_adjust_g_multcomp = 'bon')`

`results <- protein_quant(pepData = mypepData, method = 'rollup',
                         combine_fn = 'median', emeta_cols = "ProteinList")`

**Comment by evanglass** [comment]
This is kind of a note-to-self, but it seems the issue is this code
```r
n_row_emeta <- if (is.null(results$e_meta)) {
      # Use either the original or isoform e_meta depending on the input.
      if (is.null(isoformRes)) {
        nrow(unique(pepData$e_meta))
      } else {
        nrow(e_meta_iso)
      }
    } else {
      nrow(unique(results$e_meta))
    }
 ```
is using the original (non rolled up) e_meta, which means the n_row_emeta is not equal to n_row_edata, so the column gets removed. As a test I tried using `length(unique(pepData$e_meta[[emeta_cname]]))` in place of `nrow(unique(pepData$e_meta))`, but it ended up with problems further down the line (e_meta was getting duplicate rows, meaning as.proData was throwing an error).

**Comment by rarichardson92** [comment]
As it turns out, the above example is a more complex version of the problem, where sometimes the extra columns have multiple possible entries. Appending the following lines to the above example should illustrate the simpler case:

```
mypepData$e_meta$Org <- round(runif(nrow(mypepData$e_meta)), 1)*10
results <- protein_quant(pepData = mypepData, method = 'rollup', combine_fn = 'median', emeta_cols = "Org")
```

**Comment by clabornd** [comment]
Were gonna now keep those columns and paste() together their elements
